//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Ecommerce.User.Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRAND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BRAND()
        {
            this.PRODUCT_DETAIL = new HashSet<PRODUCT_DETAIL>();
        }
    
        public long BRAND_ID { get; set; }
        public string BRAND_NAME { get; set; }
        public string BRAND_NAME_UNSIGNED { get; set; }
        public Nullable<long> BRAND_LOGO { get; set; }
    
        public virtual IMAGE_STORE IMAGE_STORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_DETAIL> PRODUCT_DETAIL { get; set; }
    }
}
