//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Ecommerce.User.Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUY_BENEFIT
    {
        public long BENEFIT_ID { get; set; }
        public string BENEFIT_TITLE { get; set; }
        public string BENEFIT_CONTENT { get; set; }
    }
}
