//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Ecommerce.User.Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIE()
        {
            this.CATEGORIE1 = new HashSet<CATEGORIE>();
            this.PRODUCT_DETAIL = new HashSet<PRODUCT_DETAIL>();
        }
    
        public long CATEGORIE_ID { get; set; }
        public string CATEGORIE_NAME { get; set; }
        public string CATEGORIE_NAME_UNSIGNED { get; set; }
        public string CATEGORIE_CODE { get; set; }
        public long CATEGORIE_TYPE { get; set; }
        public Nullable<long> CATEGORIE_ROOT { get; set; }
        public string CATEGORIE_LOGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORIE> CATEGORIE1 { get; set; }
        public virtual CATEGORIE CATEGORIE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_DETAIL> PRODUCT_DETAIL { get; set; }
    }
}
