//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Ecommerce.User.Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommerceEntities : DbContext
    {
        public EcommerceEntities()
            : base("name=EcommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRAND> BRANDs { get; set; }
        public virtual DbSet<BUY_BENEFIT> BUY_BENEFIT { get; set; }
        public virtual DbSet<CATEGORIE> CATEGORIEs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<IMAGE_STORE> IMAGE_STORE { get; set; }
        public virtual DbSet<NEWSLETTER> NEWSLETTERs { get; set; }
        public virtual DbSet<ORDER_TBL> ORDER_TBL { get; set; }
        public virtual DbSet<PAY_METHOD> PAY_METHOD { get; set; }
        public virtual DbSet<PRODUCT_DETAIL> PRODUCT_DETAIL { get; set; }
        public virtual DbSet<SALE_PROMOTION_EVENT> SALE_PROMOTION_EVENT { get; set; }
        public virtual DbSet<SIZE_TYPE> SIZE_TYPE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
